### PR TITLE
Allow command line arguments using -m friendly_traceback

### LINKED ISSUE #50: Accept command line script parameters
In hackinscience.org when I check the student code I run:

```python
proc = subprocess.run(
    [
        "python3",
        "-m",
        "friendly_traceback",
        "--formatter",
        "correction_helper.friendly_traceback_markdown",
        "solution.py",
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    universal_newlines=True,
)
```

Which give them, on error, a nice Markdown output that get properly rendered and colored in the front-end, lovely.

But for some exercises I would like to pass them arguments, but it does not look supported yet. I may have time to take a look at it by myself, but probably not today, so as a first step I'm writing this issue :)

### PR DESCRIPTION
**Pull request by JulienPalard**
closes #50 

Where sould I document it?

### CODE REVIEW

**Comment by aroberge** [comment]
I will write up the documentation, including documenting my suggestion about using usercustomize.py.
It will be included in https://aroberge.github.io/friendly-traceback-docs/docs/html/usage.html 

I created a separate project (https://github.com/aroberge/friendly-traceback-docs) for the documentation.

**Comment by JulienPalard** [comment]
Interestingly, this PR fixes another issue:

When calling `python -m friendly_traceback --formatter some_formatter test.py` the `test.py` script was receiving the same `argv` as `friendly_traceback`, it will now properly receive an empty argv (with just its name).

**Comment by aroberge** [comment]
Unless I am very much mistaken, this only works for running scripts that do not used "named arguments", i.e. something like the `--formatter` argument. If this is what is desired, then the usercustomize.py`site.py approach is the only one that I can see which can work.  I will write this in the documentation, and add a link here to the corresponding commit so that you can see what changes I wrote to document this new option.

**Comment by aroberge** [comment]
Direct link to the only relevant change to documentation: https://github.com/aroberge/friendly-traceback-docs/commit/a0b6f141011d0ae30360dca1cd89eda9a3114fa5#diff-7d3008165b82862fcdec94df0ff555fe

New version: https://aroberge.github.io/friendly-traceback-docs/docs/html/usage.html

**Comment by JulienPalard** [comment]
You should mention that -- could (or should if arguments are not known), to avoid argparse parsing them.

Typically `python -m friendly_traceback foo.py --verbose` won't work, while `python -m friendly_traceback foo.py -- --verbose` will. Maybe `python -m friendly_traceback -- foo.py --verbose` is more readable and should work too (untested).

**Comment by aroberge** [comment]
Thanks, I didn't know of such a possibility. I will try it out later and, if it works, update the documentation and add relevant examples.

**Pull request merged**
